// createEmptyPAIC.ts
/*
  Este archivo sirve para que el sistema pueda crear
  el estado inicial de cualquier perfil PAIC.
 */

import type { PAICDocument } from "@/types/paic";

export function createEmptyPAIC(): PAICDocument {
  const now = new Date().toISOString();

  return {
    version : "0.1",
    createdAt : now,
    updatedAt : now,

    identity : {
      name : "",
      occupation : "",
      education : "",
      languages : [],
      location : "",
      summary : "",
    },

    preferences : {
      responseStyle : "balanced",
      tone : "friendly",
      preferredLanguage : "English",
      explanationDepth : "intermediate",
      formatting : {
        prefersBullets : true,
        prefersExamples : true,
        prefersStepByStep : true,
      },
    },

    skills : [],
    projects : [],
    goals : [],
    memories : [],

    metadata : {
      sourceProviders : [],
      exportedFrom : "paic-app",
      notes : "Empty PAIC document generated by PAIC v0.1",
    }
  };
}